### ISSUE TITLE
//@ sourceURL and //@ sourceMapURL is deprecated

### ISSUE THREAD

**Issue by xcv58** [thereactivestack/meteor-webpack#97]
I get a lot warnings in Chrome. It seems an issue with webpack itself. And it's already fixed: https://github.com/webpack/webpack/issues/91

Could we update webpack to fix this issue?

**Comment by eXon** [comment]
Yea I'll update to the last version.

**Comment by xcv58** [comment]
Thanks, I tried to update webpack today. But it doesn't work.

**Comment by eXon** [comment]
Should be fixed in 1.0.9

**Comment by jbbr** [comment]
I still have this issue. I'm on
meteor-webpack 1.0.11
meteor 1.3-rc.8
Chrome 50

**Comment by menelike** [comment]
this issue has been fixed with [webpack 1.13.0](https://github.com/webpack/webpack/issues/91#issuecomment-212184341), an update may be needed here

**Comment by flexlee** [comment]
please update webpack to 1.13.0, I'm getting a lot of errors in chrome. Thanks.

**Comment by eXon** [comment]
@flexlee run `npm update` :)
